language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  #- sudo apt-get install -y python-gdal python-numpy python-pandas
  #- sudo apt-get install -y python3-gdal python3-numpy python3-pandas
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
addons:
  apt:
    sources:
      - python-gdal
      - python-numpy
      - python-pandas
      - python3-gdal
      - python3-numpy
      - python3-pandas
