language: python
python: 2.7
sudo: required
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo apt-get install -y python-gdal python-numpy python-pandas python-virtualenv
  - sudo apt-get install -y python3-gdal python3-numpy
install:
  - pip install tox
  - pip install pandas
before_script:
  - test/support/setup_deps.sh
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
